---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: mysql-secrets
   labels:
     app: mysql-secrets
 spec:
   replicas: 1
   strategy:
         type: RollingUpdate
         rollingUpdate:
            maxSurge: 1
   selector:
      matchLabels:
        app: mysql-secrets
   template:
     metadata:
       labels:
         app: mysql-secrets

     spec:
      containers:
         - name: mysql-secrets
           image: mysql
           imagePullPolicy: Always
           ports:
             - containerPort: 3306

           env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mysqlrootpass
                 key: rootpass
           - name: MYSQL_DATABASE
             value: testing

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-secrets
  labels:
    app: mysql-secrets
spec:
  selector:
    app: mysql-secrets
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer
