apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
  labels:
    app: nginx2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  type: LoadBalancer
  selector:
    app: nginx2
